#vaadin.launch-browser=true
spring.application.name=WebsiteBooksManager



app.upload.dir=${java.io.tmpdir}



#Basic Server Config
#The port you want to use for HTTPS
server.port=443
server.forward-headers-strategy=framework
#Pointing to the file we just created
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.enabled=true
#This matches the "-name" flag you used in the OpenSSL command
server.ssl.key-alias=spring-boot